# Generated by Django 4.1.5 on 2023-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCommunicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=25, null=True)),
                ('pn_title', models.CharField(blank=True, help_text='Push notification title used only for Unified channel', max_length=25, null=True)),
                ('template_used', models.CharField(blank=True, max_length=10, null=True)),
                ('enable_bcc_emails', models.BooleanField(default=False, help_text="If enabled, will send copy of email to ADMIN email-ids mentioned in settings.py file. Don't enablethis for loyalty emails.")),
                ('enable_cc_emails', models.BooleanField(default=True, help_text='If enabled, will send copy of email to email ids provided in cc_email in bind_vars')),
                ('utm_params', models.CharField(blank=True, max_length=50, null=True)),
                ('send_as_async', models.BooleanField(default=False, help_text='If enabled, will send async mail using queue')),
                ('moengage_msg', models.CharField(blank=True, max_length=20, null=True)),
                ('gamooga_msg', models.CharField(blank=True, max_length=20, null=True)),
                ('konotor_msg', models.CharField(blank=True, help_text='Deprecated no need to provide this', max_length=20, null=True)),
                ('deeplink', models.CharField(blank=True, max_length=10, null=True)),
                ('pn_project', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=25, null=True)),
                ('enable_pn_max', models.BooleanField(default=False, help_text='If enabled, any number of PNs can be send')),
                ('email_template1', models.CharField(blank=True, max_length=50, null=True)),
                ('email_template2', models.CharField(blank=True, max_length=50, null=True)),
                ('sms_template', models.CharField(blank=True, max_length=10, null=True)),
                ('pn_template', models.CharField(blank=True, max_length=10, null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('sms_provider', models.IntegerField(null=True)),
                ('send_pn', models.BooleanField(default=False)),
                ('send_whatsapp_message', models.BooleanField(default=False)),
                ('whatsapp_template_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_html_template', models.TextField(blank=True, null=True)),
                ('variables_used', models.CharField(blank=True, max_length=50, null=True)),
                ('utm_params_pn', models.CharField(blank=True, max_length=50, null=True)),
                ('utm_params_sms', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
